# Site settings
description: A blog about lorem ipsum dolor sit amet
url: ""

# User settings
username: Desiree Santos
user_title:
  pt: Desenvolvedora | IoT especialista | Maker
  en: Software Engineer | IoT especialist | Maker
email: desisant@gmail.com
twitter_username: desisant
github_username:  desireesantos

lang:   ['pt', 'en']
