# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://desireesantos.com" # the base hostname & protocol for your site 

# User settings
username: Desiree Santos
user_title:
  pt: Desenvolvedora | IoT especialista | Maker
  en: Software Engineer | IoT especialist | Maker
email: desisant@gmail.com
twitter_username: desisant
github_username:  desireesantos

lang:   ['pt', 'en']
