# Site settings
description: A blog about lorem ipsum dolor sit amet
url: ""

# User settings
username: Desiree Santos
user_title:
  pt: Desenvolvedora | IoT especialista
  en: Software Developer | IoT especialist
index:
  pt: index.html
  en: index_en.html  
email: desisant@gmail.com
twitter_username: desisant
github_username:  desireesantos

lang:   ['pt', 'en']
