# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Desiree Santos
email: desisant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Consultora de software na  ThoughtWorks
  Mestranda em Ciência da Computação (PUCRS) e formada em Sistemas para Internet (CEFET/RJ). 
  Entusiasta de Metodologias ágeis e apaixonada por desenvolvimento de software, 
  atualmente trabalha como consultora de software na ThoughtWorks Brasil. 
  Militante no movimento de open software/hardware, desenvolvendo projetos voltados para Internet das coisas. 
  Coordena a comunidade de arduino no RJ (arduinrio) e faz parte do hackerspace de Porto Alegre Matehacker. 
  Participa da comunidade nacional e internacional de embarcados.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://desireesantos.com" # the base hostname & protocol for your site
twitter_username: desisant
github_username:  desireesantos

# Build settings
markdown: kramdown
