
# Site settings
title: Desiree Santos
email: desisant@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://desireesantos.com" # the base hostname & protocol for your site
twitter_username: desisant
github_username:  desireesantos
facebook_username: desiree.santos.589
# Build settings
markdown: kramdown
