# Site settings
description: Desiree Santos Blog
url;: http://desireesantos.com

# User settings
username: Desiree Santos
twitter_username: desisant
github_username:  desireesantos
email: desisant@gmail.com
user_title:
  pt: Developer full stack | Maker
  en: Software Developer full stack | Maker

#index setup
index_page:
  pt: /index.html
  en: /en/index.html

#About setup
about_page:
  pt: ./sobre.html
  en: ./en/about.html
about:
  pt: Sobre
  en: About

lang:   ['pt', 'en']

