# Site settings
description: Desiree Santos Blog

# User settings
username: Desiree Santos
user_title:
  pt: Developer full stack | Maker
  en: Software Developer full stack | Maker
index:
  pt: index.html
  en: index_en.html  
email: desisant@gmail.com
twitter_username: desisant
github_username:  desireesantos

lang:   ['pt', 'en']
