title: Desiree
email: desisant@gmail.com
index:
  pt: index.html
  en: index_en.html
feed:
  pt: /feed.xml
  en: /feed.xml
baseurl: ""
url: ""
twitter_username: desisant
github_username:  desireesantos

# Build settings
markdown: kramdown
